#!/usr/bin/env ruby
require 'open3'
require 'pry'
require 'pry-byebug'
require 'fileutils'

def yes?(prompt)
  puts prompt
  reply = gets
  ["Yes", "yes", "Y", "y"].include? reply.chomp
end

if yes?("Do you want to deploy .irbrc?")
  # puts "Hello, world!"
  if File.exist?("#{ENV.fetch('HOME')}/.irbrc")
    # binding.pry
    puts ".irbrc exists, backing up to .irbrc.bak"
    File.rename("#{ENV.fetch('HOME')}/.irbrc", "#{ENV.fetch('HOME')}/.irbrc.bak")
    puts "copying .irbrc to #{ENV.fetch('HOME')}/.irbrc"
    FileUtils.cp(".irbrc", "#{ENV.fetch('HOME')}/.irbrc")
  else
    puts "File does not exist"
    FileUtils.cp(".irbrc", "#{ENV.fetch('HOME')}/.irbrc")
  end
end

if yes?("Do you want to deploy .railsrc?")
  # puts "Hello, world!"
  if File.exist?("#{ENV.fetch('HOME')}/.railsrc")
    # binding.pry
    puts ".irbrc exists, backing up to .irbrc.bak"
    File.rename("#{ENV.fetch('HOME')}/.railsrc", "#{ENV.fetch('HOME')}/.railsrc.bak")
    puts "copying .railsrc to #{ENV.fetch('HOME')}/.railsrc"
    FileUtils.cp(".railsrc", "#{ENV.fetch('HOME')}/.railsrc")
  else
    puts "File does not exist"
    FileUtils.cp(".railsrc", "#{ENV.fetch('HOME')}/.railsrc")
  end
end
