#!/bin/bash

bin/bundle add dalli

bin/bundle add sorbet-runtime

bin/bundle add sorbet --group development

gem 'tapioca', require: false, :group => :development

bin/bundle install

bin/bundle tapioca init
