#!/usr/bin/env ruby
require 'open3'
require 'pry'
require 'pry-byebug'
require 'fileutils'


if File.exist?("#{ENV.fetch('HOME')}/.irbrc")
  puts ".irbrc exists, backing up to .irbrc.bak"
  File.rename("#{ENV.fetch('HOME')}/.irbrc", "#{ENV.fetch('HOME')}/.irbrc.bak")
  puts "copying .irbrc to #{ENV.fetch('HOME')}/.irbrc"
  FileUtils.cp(".irbrc", "#{ENV.fetch('HOME')}/.irbrc")
else
  puts "File does not exist"
  FileUtils.cp(".irbrc", "#{ENV.fetch('HOME')}/.irbrc")
end


if File.exist?("#{ENV.fetch('HOME')}/.railsrc")
  puts ".irbrc exists, backing up to .irbrc.bak"
  File.rename("#{ENV.fetch('HOME')}/.railsrc", "#{ENV.fetch('HOME')}/.railsrc.bak")
  puts "copying .railsrc to #{ENV.fetch('HOME')}/.railsrc"
  FileUtils.cp(".railsrc", "#{ENV.fetch('HOME')}/.railsrc")
else
  puts "File does not exist"
  FileUtils.cp(".railsrc", "#{ENV.fetch('HOME')}/.railsrc")
end
