#!/bin/bash

mkdir -p ~/.config/nvim

cp -p .devcontainer/init.vim ~/.config/nvim/init.vim 

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'